sfdx-source/isvte_falcon/main/default/objects/Account/fields/DW_Email__c.field-meta.xml
<CustomField>
    <fullName>DW_Email__c</fullName>
    <label>DW Email</label>
    <type>Email</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/Account/fields/DW_Password__c.field-meta.xml
<CustomField>
    <fullName>DW_Password__c</fullName>
    <description>DriveWealth Password</description>
    <inlineHelpText>DriveWealth Password</inlineHelpText>
    <label>DW Password</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/Account/fields/DW_Total_Practice_Accounts__c.field-meta.xml
<CustomField>
    <fullName>DW_Total_Practice_Accounts__c</fullName>
    <label>DW Total Practice Accounts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/Account/fields/DW_User_ID__c.field-meta.xml
<CustomField>
    <fullName>DW_User_ID__c</fullName>
    <description>DriveWealth User ID</description>
    <externalId>true</externalId>
    <inlineHelpText>DriveWealth User ID</inlineHelpText>
    <label>DW User ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/Account/fields/DW_Username__c.field-meta.xml
<CustomField>
    <fullName>DW_Username__c</fullName>
    <description>DriveWealth Username</description>
    <inlineHelpText>DriveWealth Username</inlineHelpText>
    <label>DW Username</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Account__c/DW_Account__c.object-meta.xml
<CustomObject>
    <description>Object to store information about DriveWealth Accounts</description>
    <label>DW Account</label>
    <nameField>
        <label>DW Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DW Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sfdx-source/isvte_falcon/main/default/objects/DW_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Salesforce Account this DriveWealth account belongs to</description>
    <inlineHelpText>Salesforce Account this DriveWealth account belongs to</inlineHelpText>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DW Accounts</relationshipLabel>
    <relationshipName>DW_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Account__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <description>DriveWealth Account ID</description>
    <externalId>true</externalId>
    <inlineHelpText>DriveWealth Account ID</inlineHelpText>
    <label>Account ID</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Account__c/fields/Account_No__c.field-meta.xml
<CustomField>
    <fullName>Account_No__c</fullName>
    <label>Account No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>DriveWealth accountType; 1 - Practice or 2 - Live.</description>
    <inlineHelpText>DriveWealth accountType; 1 - Practice or 2 - Live.</inlineHelpText>
    <label>Account Type</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Account__c/fields/Created_When__c.field-meta.xml
<CustomField>
    <fullName>Created_When__c</fullName>
    <label>Created When</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/DW_Order__c.object-meta.xml
<CustomObject>
    <label>DW Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>DW Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DW Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DW Orders</relationshipLabel>
    <relationshipName>DW_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/DW_Account__c.field-meta.xml
<CustomField>
    <fullName>DW_Account__c</fullName>
    <label>DW Account</label>
    <referenceTo>DW_Account__c</referenceTo>
    <relationshipLabel>DW Orders</relationshipLabel>
    <relationshipName>DW_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Executed_When__c.field-meta.xml
<CustomField>
    <fullName>Executed_When__c</fullName>
    <defaultValue>"Not Executed"</defaultValue>
    <label>Executed When</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Instrument_Name__c.field-meta.xml
<CustomField>
    <fullName>Instrument_Name__c</fullName>
    <label>Instrument Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Instrument_Symbol__c.field-meta.xml
<CustomField>
    <fullName>Instrument_Symbol__c</fullName>
    <label>Instrument Symbol</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Order_ID__c.field-meta.xml
<CustomField>
    <fullName>Order_ID__c</fullName>
    <externalId>true</externalId>
    <label>Order ID</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Order_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Order_Quantity__c</fullName>
    <label>Order Quantity</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <description>"0" - New, "1" - Partial Fill, "2" - Fill, "4" - Canceled, "8" - Rejected.</description>
    <inlineHelpText>"0" - New, "1" - Partial Fill, "2" - Fill, "4" - Canceled, "8" - Rejected.</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Fill</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Partial Fill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Market Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Side__c.field-meta.xml
<CustomField>
    <fullName>Side__c</fullName>
    <label>Side</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/isvte_falcon/main/default/classes/DataQuery.cls
/**
  * Class to build all the queries that we will be using
  * This is helpful as we will only need to keep all SOQL queries in one place in case we need to add/remove columns
  *
  * This class will also take care of CRUD/FLS as needed
 */
public with sharing class DataQuery {

    /**
      * Return User information for current logged in user
      *
      *
      * Note: Use try/catch in calling function to trap any Exceptions
      * This funciton can raise SFDCAccessControlException or Eception
      *
      * @param UserID ID for record to return
      * @return Account
     */

    public static User getUser(ID UserId){

        //CRUD/FLS check
        Util.AccessController.assertAuthorizedToView(
                Schema.User.getSobjectType(),
                new List<Schema.SobjectField>{
                        Schema.User.fields.AccountId
                }
        );

        User u = [SELECT AccountId FROM User WHERE Id = :UserId];

        return u;
    }

    /**
      * Return DriveWealth Account List created for an Account based on Account ID
      *
      *
      * Note: Use try/catch in calling function to trap any Exceptions
      * This funciton can raise SFDCAccessControlException or Eception
      *
      * @param AccountID ID of account
      *
      * @return Account
     */

    public static Account getAccount(Id AccountId){

        //CRUD/FLS check
        Util.AccessController.assertAuthorizedToView(
            Schema.Account.getSobjectType(),
            new List<Schema.SobjectField>{
                    Schema.Account.fields.Name, Schema.Account.fields.DW_Username__c,
                    Schema.Account.fields.DW_Password__c, Schema.Account.fields.DW_User_ID__c,
                    Schema.Account.fields.DW_Total_Practice_Accounts__c, Schema.Account.fields.DW_Email__c
            }
        );
        //CRUD/FLS Check
        Util.AccessController.assertAuthorizedToView(
                Schema.DW_Account__c.getSobjectType(),
                new List<Schema.SobjectField>{
                        Schema.DW_Account__c.fields.Name,
                        Schema.DW_Account__c.fields.Account_No__c,
                        Schema.DW_Account__c.fields.Account_Type__c,
                        Schema.DW_Account__c.fields.Created_When__c

                }
        );

        Account a;
        List<Account> listAcc =  [select ID, Name, DW_Email__c,  DW_Username__c, DW_Password__c, DW_User_ID__c, DW_Total_Practice_Accounts__c, (select Id, Name, Account_No__c, Account_Type__c, Created_When__c from DW_Accounts__r) from Account WHERE Id=:AccountId];
        if(listAcc.size() > 0 ){
            a = listAcc[0];
        }
        return a;
    }
    /**
      * Return DriveWealth Account information created for an Account based on DW Account ID
      *
      * Note: Use try/catch in calling function to trap any Exceptions
      * This funciton can raise SFDCAccessControlException or Eception
      *
      * @param AccountID ID of account
      *
      * @return DW_Account__c
     */

    public static DW_Account__c getDWAccount(Id DWAccountID){

        //CRUD/FLS check
        //Chek for DW Account
        Util.AccessController.assertAuthorizedToView(
                Schema.DW_Account__c.getSobjectType(),
                new List<Schema.SobjectField>{
                        Schema.DW_Account__c.fields.Name, Schema.DW_Account__c.fields.Account__c,
                        Schema.DW_Account__c.fields.Account_ID__c, Schema.DW_Account__c.fields.Account_No__c,
                        Schema.DW_Account__c.fields.Account_Type__c
                }
        );
        //Check for account as we also need it for that
        Util.AccessController.assertAuthorizedToView(
                Schema.Account.getSobjectType(),
                new List<Schema.SobjectField>{
                        Schema.Account.fields.Name, Schema.Account.fields.DW_User_ID__c,
                        Schema.Account.fields.DW_Username__c, Schema.Account.fields.DW_Password__c
                }
        );
        return [select ID,Name,Account__c,Account_ID__c, Account_No__c, Account_Type__c, Account__r.DW_User_ID__c,
                        Account__r.DW_Username__c, Account__r.dW_Password__c
                    from DW_Account__c WHERE Id=:DWAccountID];
    }

    /**
     * return list of all orders associated with an account
     */

    public static  Map<Id, DW_Order__c> getOrders(Id AccountID) {
        //CRUD/FLS check
        //Chek for DW Account
        Util.AccessController.assertAuthorizedToView(
                Schema.DW_Account__c.getSobjectType(),
                new List<Schema.SobjectField>{
                        Schema.DW_Account__c.fields.Name
                }
        );

        //Chek for Order
        Util.AccessController.assertAuthorizedToView(
                Schema.DW_Order__c.getSobjectType(),
                new List<Schema.SobjectField>{
                        Schema.DW_Order__c.fields.DW_Account__c, Schema.DW_Order__c.fields.Instrument_Name__c,
                        Schema.DW_Order__c.fields.Order_Quantity__c, Schema.DW_Order__c.fields.Order_ID__c,
                        Schema.DW_Order__c.fields.Order_Type__c, Schema.DW_Order__c.fields.Side__c,
                        Schema.DW_Order__c.fields.Order_Status__c, Schema.DW_Order__c.fields.Executed_When__c
                }
        );

        //CRUD/FLS check

        Map<Id, DW_Order__c> retVal = new  Map<Id, DW_Order__c>(
                [Select Id, DW_Account__r.Name, DW_Account__c, Instrument_Name__c, Order_Quantity__c, Order_ID__c,
                        Order_Type__c, Side__c, Order_Status__c, Executed_When__c, CreatedDate, Instrument_Symbol__c
                    FROM DW_Order__c where Account__c=:AccountID
                    ORDER BY CreatedDate ASC]
        );
        return retval;
    }

    /**
     * return order based on Order ID
     */
    public static  DW_Order__c getOrder(Id OrderID) {

        //Chek for Order
        Util.AccessController.assertAuthorizedToView(
                Schema.DW_Order__c.getSobjectType(),
                new List<Schema.SobjectField>{
                        Schema.DW_Order__c.fields.Name
                }
        );

        DW_Order__c  dwOrder;
        List<DW_Order__c> dwOrderList = [Select Id, Order_ID__c FROM DW_Order__c where Id=:OrderId];
        if(dwOrderList.size() > 0){
            dwOrder = dwOrderList[0];
        }
        return dwOrder;
    }
}