sfdx-source/isvte_falcon/main/default/objects/Account/fields/DW_Password__c.field-meta.xml
<CustomField>
    <fullName>DW_Password__c</fullName>
    <description>DriveWealth Password</description>
    <inlineHelpText>DriveWealth Password</inlineHelpText>
    <label>DW Password</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/Account/fields/DW_Username__c.field-meta.xml
<CustomField>
    <fullName>DW_Username__c</fullName>
    <description>DriveWealth Username</description>
    <inlineHelpText>DriveWealth Username</inlineHelpText>
    <label>DW Username</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/classes/DWAccountTriggerHandler.cls
public with sharing class DWAccountTriggerHandler {
    public static void handleBeforeInsert(List<Account> accListNew){
        //Always encrypt username/password on new account
        for(Account acc: accListNew){
            if(String.isNotBlank(acc.DW_Username__c)) {
                acc.DW_Username__c = DriveWealth.encryptString(acc.DW_Username__c);
            }
            if(String.isNotBlank(acc.DW_Password__c)) {
                acc.DW_Password__c = DriveWealth.encryptString(acc.DW_Password__c);
            }
        }
    }

    public static void handleBeforeUpdate(List<Account> accListNew, Map<Id, Account> accListNewMap, Map<Id, Account> accListOldMap){
        //Only encrypt if username/password fields have been changed
        for(Account acc: accListNew){
            if(String.isNotBlank(acc.DW_Username__c) && accListNewMap.get( acc.Id ).DW_Username__c != accListOldMap.get( acc.Id ).DW_Username__c ){
                //Username has changed
                acc.DW_Username__c = DriveWealth.encryptString(acc.DW_Username__c);
            }
            if(String.isNotBlank(acc.DW_Password__c) && accListNewMap.get( acc.Id).DW_Password__c != accListOldMap.get(  acc.Id ).DW_Password__c ){
                //Password has changed
                acc.DW_Password__c  = DriveWealth.encryptString(acc.DW_Password__c);
            }
        }
    }
}