sfdx-source/isvte_falcon/main/default/objects/Account/fields/DW_Password__c.field-meta.xml
<CustomField>
    <fullName>DW_Password__c</fullName>
    <description>DriveWealth Password</description>
    <inlineHelpText>DriveWealth Password</inlineHelpText>
    <label>DW Password</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/Account/fields/DW_User_ID__c.field-meta.xml
<CustomField>
    <fullName>DW_User_ID__c</fullName>
    <description>DriveWealth User ID</description>
    <externalId>true</externalId>
    <inlineHelpText>DriveWealth User ID</inlineHelpText>
    <label>DW User ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/Account/fields/DW_Username__c.field-meta.xml
<CustomField>
    <fullName>DW_Username__c</fullName>
    <description>DriveWealth Username</description>
    <inlineHelpText>DriveWealth Username</inlineHelpText>
    <label>DW Username</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DriveWealth__c/DriveWealth__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>DriveWealth</label>
</CustomObject>

sfdx-source/isvte_falcon/main/default/objects/DriveWealth__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Account__c/DW_Account__c.object-meta.xml
<CustomObject>
    <description>Object to store information about DriveWealth Accounts</description>
    <label>DW Account</label>
    <nameField>
        <label>DW Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DW Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sfdx-source/isvte_falcon/main/default/objects/DW_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Salesforce Account this DriveWealth account belongs to</description>
    <inlineHelpText>Salesforce Account this DriveWealth account belongs to</inlineHelpText>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DW Accounts</relationshipLabel>
    <relationshipName>DW_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Account__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <description>DriveWealth Account ID</description>
    <externalId>true</externalId>
    <inlineHelpText>DriveWealth Account ID</inlineHelpText>
    <label>Account ID</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Account__c/fields/Account_No__c.field-meta.xml
<CustomField>
    <fullName>Account_No__c</fullName>
    <label>Account No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>DriveWealth accountType; 1 - Practice or 2 - Live.</description>
    <inlineHelpText>DriveWealth accountType; 1 - Practice or 2 - Live.</inlineHelpText>
    <label>Account Type</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/DW_Order__c.object-meta.xml
<CustomObject>
    <label>DW Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>DW Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DW Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DW Orders</relationshipLabel>
    <relationshipName>DW_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/DW_Account__c.field-meta.xml
<CustomField>
    <fullName>DW_Account__c</fullName>
    <label>DW Account</label>
    <referenceTo>DW_Account__c</referenceTo>
    <relationshipLabel>DW Orders</relationshipLabel>
    <relationshipName>DW_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Order_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Order_Quantity__c</fullName>
    <label>Order Quantity</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Market Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Side__c.field-meta.xml
<CustomField>
    <fullName>Side__c</fullName>
    <label>Side</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/isvte_falcon/main/default/classes/DWCreateOrder_Controller_Test.cls
@isTest
private class DWCreateOrder_Controller_Test {
    @testSetup
    private static void dataSetup(){
        DriveWealth__c dw = new DriveWealth__c();
        dw.Endpoint__c = 'https://api.drivewealth.io/v1/'; 
        insert dw;

        List<DW_Account__c> dwAccountList = new List<DW_Account__c>();


        List<Account> listAcc = new List<Account>();
        for(Integer i=0;i<10; i++){
            Account acc = new Account();
            acc.Name = 'Account A' + i;
            acc.DW_Username__c = 'abc1234';
            acc.DW_Password__c = 'abc1234';

            //This ID matches the data from HTTPMockResponse in createSession()
            acc.DW_User_ID__c = '02e57c7d-d071-4c63-b491-1194a9939ea5';

            listAcc.add(acc);

        }

        insert listAcc;

        for(Integer i=0; i<10; i++){

            DW_Account__c dwAccount = new DW_Account__c();
            dwAccount.Name = 'Test DW Account';

            dwAccount.Account__c = listAcc[i].Id;
            dwAccount.Account_No__c = '1111';
            dwAccount.Account_ID__c = '1111';
            dwAccount.Account_Type__c = 1;
            dwAccountList.add(dwAccount);
        }
        insert dwAccountList;

    }
    @isTest
    private static void createOrderController_submitOrder_positive(){

        Account acc = [SELECT Id, DW_Username__c, DW_Password__C from Account where name='Account A0' limit 1];
        DW_Account__c dwAccount = [SELECT Id, Account_No__c from DW_Account__c where Account__c=:acc.Id];

        Map<String, Object> orderInfo = new Map<String,Object>();
        orderInfo.put('DW_Account__c', dwAccount.Id);
        orderInfo.put('Order_Type__c', 1);
        orderInfo.put('Side__c', 'B' );
        orderInfo.put('Order_Quantity__c', 11);
        orderInfo.put('Comment__c', '');

        DriveWealthJsonInstrument instrument = new DriveWealthJsonInstrument();
        instrument.instrumentID = 'IDID';
        instrument.Name = 'INS Name';
        instrument.symbol = 'CRM';

        Map<String, Object> data = new Map<String, Object>{'mode'=>'submitOrder', 'acc' => acc,
                                                'orderInfo' => orderInfo,
                                                'instrument' => JSON.serialize(instrument)
                                        };

        Test.setMock(HTTPCalloutMock.class, new HTTPMockResponse());


        Test.startTest();

        ETLC_ApexBridge_Data d1 = new ETLC_ApexBridge_Data();
        d1.operation = 'DWCreateOrder_Controller';
        d1.input = ETLC_ApexBridge_Data.encodeData(data);
        d1.debug = true;


        String strD2 =  ETLC_ApexBridge_Controller.execute(d1.toJson());
        ETLC_ApexBridge_Data d2 = ETLC_ApexBridge_Data.fromJSON(strD2);

        DriveWealthJsonMarketOrder retVal = (DriveWealthJsonMarketOrder)ETLC_ApexBridge_Data.decodeData(d2.output, DriveWealthJsonMarketOrder.class);
        Test.stopTest();

        System.assertEquals(1, [select id from dw_order__c].size());
        System.assertEquals('06926627-e950-48f3-9c53-b679f61120ec', retVal.instrumentID);

    }
    @isTest
    private static void createOrderController_getAccount_negative(){
        Id AccountID = '00141000007RP8w';//WRONG ID

        Map<String, String> data = new Map<String, String>{'mode'=>'getAccount', 'AccountID' => AccountID};

        ETLC_ApexBridge_Data d1 = new ETLC_ApexBridge_Data();
        d1.operation = 'DWCreateOrder_Controller';
        d1.input = ETLC_ApexBridge_Data.encodeData(data);
        d1.debug = true;

        String strD2 =  ETLC_ApexBridge_Controller.execute(d1.toJson());
        ETLC_ApexBridge_Data d2 = ETLC_ApexBridge_Data.fromJSON(strD2);
        Account a = (Account)ETLC_ApexBridge_Data.decodeData(d2.output, Account.class);

        System.assertEquals(null, a);
    }

    @isTest
    private static void createOrderController_getAccount_positive(){
        Account acc = [SELECT Id, DW_Username__c, DW_Password__C from Account where name='Account A0' limit 1];


        Map<String, String> data = new Map<String, String>{'mode'=>'getAccount', 'AccountID' => acc.Id};

        ETLC_ApexBridge_Data d1 = new ETLC_ApexBridge_Data();
        d1.operation = 'DWCreateOrder_Controller';
        d1.input = ETLC_ApexBridge_Data.encodeData(data);
        d1.debug = true;

        String strD2 =  ETLC_ApexBridge_Controller.execute(d1.toJson());
        ETLC_ApexBridge_Data d2 = ETLC_ApexBridge_Data.fromJSON(strD2);
        Account a = (Account)ETLC_ApexBridge_Data.decodeData(d2.output, Account.class);
        System.assertEquals('Account A0', a.Name);
        System.assertEquals(1, a.DW_Accounts__r.size());
    }


}