sfdx-source/isvte_falcon/main/default/objects/Account/fields/DW_Password__c.field-meta.xml
<CustomField>
    <fullName>DW_Password__c</fullName>
    <description>DriveWealth Password</description>
    <inlineHelpText>DriveWealth Password</inlineHelpText>
    <label>DW Password</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/Account/fields/DW_User_ID__c.field-meta.xml
<CustomField>
    <fullName>DW_User_ID__c</fullName>
    <description>DriveWealth User ID</description>
    <externalId>true</externalId>
    <inlineHelpText>DriveWealth User ID</inlineHelpText>
    <label>DW User ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/Account/fields/DW_Username__c.field-meta.xml
<CustomField>
    <fullName>DW_Username__c</fullName>
    <description>DriveWealth Username</description>
    <inlineHelpText>DriveWealth Username</inlineHelpText>
    <label>DW Username</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DriveWealth__c/DriveWealth__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>DriveWealth</label>
</CustomObject>

sfdx-source/isvte_falcon/main/default/objects/DriveWealth__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Account__c/DW_Account__c.object-meta.xml
<CustomObject>
    <description>Object to store information about DriveWealth Accounts</description>
    <label>DW Account</label>
    <nameField>
        <label>DW Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DW Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sfdx-source/isvte_falcon/main/default/objects/DW_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Salesforce Account this DriveWealth account belongs to</description>
    <inlineHelpText>Salesforce Account this DriveWealth account belongs to</inlineHelpText>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DW Accounts</relationshipLabel>
    <relationshipName>DW_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/DW_Order__c.object-meta.xml
<CustomObject>
    <label>DW Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>DW Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DW Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DW Orders</relationshipLabel>
    <relationshipName>DW_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/DW_Account__c.field-meta.xml
<CustomField>
    <fullName>DW_Account__c</fullName>
    <label>DW Account</label>
    <referenceTo>DW_Account__c</referenceTo>
    <relationshipLabel>DW Orders</relationshipLabel>
    <relationshipName>DW_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Expires_Time_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Expires_Time_Stamp__c</fullName>
    <label>Expires Time Stamp</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Instrument_ID__c.field-meta.xml
<CustomField>
    <fullName>Instrument_ID__c</fullName>
    <label>Instrument ID</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Instrument_Name__c.field-meta.xml
<CustomField>
    <fullName>Instrument_Name__c</fullName>
    <label>Instrument Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Order_ID__c.field-meta.xml
<CustomField>
    <fullName>Order_ID__c</fullName>
    <externalId>true</externalId>
    <label>Order ID</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Order_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Order_Quantity__c</fullName>
    <label>Order Quantity</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <description>"0" - New, "1" - Partial Fill, "2" - Fill, "4" - Canceled, "8" - Rejected.</description>
    <inlineHelpText>"0" - New, "1" - Partial Fill, "2" - Fill, "4" - Canceled, "8" - Rejected.</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Fill</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Partial Fill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Market Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/isvte_falcon/main/default/objects/DW_Order__c/fields/Side__c.field-meta.xml
<CustomField>
    <fullName>Side__c</fullName>
    <label>Side</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/isvte_falcon/main/default/classes/DWOrderList_Controller_Test.cls
@isTest
private class DWOrderList_Controller_Test {

    @testSetup
    private static void doSetup(){ 
        //Need for API calls
        DriveWealth__c dw = new DriveWealth__c();
        dw.Endpoint__c = 'https://api.drivewealth.io/v1/'; 
        insert dw;

        Account a = new Account();
        a.Name = 'Account A0';
        a.DW_Username__c = 'username';
        a.DW_Password__c = 'password';
        insert a;

        DW_Account__c dwAccount = new DW_Account__c();
        dwAccount.Name = 'DW Account';
        dwAccount.Account__c = a.Id;
        insert dwAccount;

        DW_Order__c dwOrder = new DW_Order__c();
        dwOrder.Account__c = a.Id;
        dwOrder.DW_Account__c = dwAccount.Id;
        dwOrder.Order_ID__c = 'a00';//Need order ID to start with a for MockResponse to work
        dwOrder.Order_Quantity__c = 12;
        dwOrder.Order_Type__c = 'Market Order';
        dwOrder.Side__c = 'Sell';
        dwOrder.Expires_Time_Stamp__c = '';
        dwOrder.Instrument_ID__c = 'instrumentID';
        dwOrder.Instrument_Name__c = 'instrument.name';
        insert dwOrder;

    }
    @istest
    private static void fetchStatus_positive() {
        Util.debug = true;
        Account acc = [SELECT Id, DW_Username__c, DW_Password__C, DW_User_ID__c from Account where name='Account A0' limit 1];
        DW_Order__c dwOrder = [select id, Order_Status__c from DW_Order__c where Account__c=:acc.Id];
        System.assertEquals('New', dwOrder.Order_Status__c);

        Map<String, Object> data = new Map<String, Object>{'mode'=>'fetchStatus', 'OrderID' => dwOrder.Id, 'AccountID'=>acc.Id};

        Test.setMock(HTTPCalloutMock.class, new HTTPMockResponse());


        Test.startTest();

        ETLC_ApexBridge_Data d1 = new ETLC_ApexBridge_Data();
        d1.operation = 'DWOrderList_Controller';
        d1.input = ETLC_ApexBridge_Data.encodeData(data);
        d1.debug = true;

        String strD2 =  ETLC_ApexBridge_Controller.execute(d1.toJson());
        ETLC_ApexBridge_Data d2 = ETLC_ApexBridge_Data.fromJSON(strD2);
        DriveWealthJsonOrderStatus retVal = (DriveWealthJsonOrderStatus)ETLC_ApexBridge_Data.decodeData(d2.output, DriveWealthJsonOrderStatus.class);

        test.stopTest();

        System.assertEquals('Rejected', retVal.ordStatus);

        //When saving to database, we change it to readbale form so testing for Rejected
        DW_Order__c dwOrder1 = [select id, Order_Status__c from DW_Order__c where Account__c=:acc.Id];
        System.assertEquals('Rejected', dwOrder1.Order_Status__c);
    }

    @istest
    private static void getOrders_positive() {
        Account acc = [SELECT Id, DW_Username__c, DW_Password__C, DW_User_ID__c from Account where name='Account A0' limit 1];
        DW_Order__c dwOrder = [select id from DW_Order__c where Account__c=:acc.Id];

        Map<String, Object> data = new Map<String, Object>{'mode'=>'getOrders', 'AccountID' => acc.Id};

        ETLC_ApexBridge_Data d1 = new ETLC_ApexBridge_Data();
        d1.operation = 'DWOrderList_Controller';
        d1.input = ETLC_ApexBridge_Data.encodeData(data);
        d1.debug = true;

        String strD2 =  ETLC_ApexBridge_Controller.execute(d1.toJson());
        ETLC_ApexBridge_Data d2 = ETLC_ApexBridge_Data.fromJSON(strD2);
        MAP<Id, DW_Order__c> retVal = (MAP<Id, DW_Order__c>)ETLC_ApexBridge_Data.decodeData(d2.output, MAP<Id, DW_Order__c>.class);
        DW_Order__c retOrder = retVal.get(dwOrder.Id);
        System.assertEquals(12, retOrder.Order_Quantity__c);
    }

}